### ISSUE TITLE
Microlitter type:styrofoam (BODCNVS-1306)

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#17]
We would like to evaluate if it is possible to modify the term "microplastic styrofoam" from the existing H01 vocabulary (http://vocab.nerc.ac.uk/collection/H01/current/H0100006/) to clarify that it is related to both foam and styrofoam or even to change the name of the term to "microplastic foam" and in the definition include: all types of foam including styrofoam. We would prefer the second option. What do you think @gwemon ?
Thanks!
Eugenia and Matteo

@mattevi78

**Comment by gwemon** [comment]
@mmolinajack  @mattevi78 I can't see any problem in broadening this concept to "microplastic foam" or rather "microplastic foams" to be aligned with the approach we took for the other members of this vocabulary. i.e. plural form.
So preflabel will be changed from "microplastic styrofoam" to "microplastic foams"
and defintion from "Micro-litter particles of styrofoam" to "Any kind of micro-litter particle made of plastic foam, including styrofoam."
We will make these changes tomorrow unless we hear otherwise.

**Comment by mmolinajack** [comment]
Perfect! Thank you @gwemon

**Comment by gwemon** [comment]
Changes are published.
